version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.6.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ../elasticsearch/data:/usr/share/elasticsearch/data
      - ../elasticsearch/plugins/analysis-ik:/usr/share/elasticsearch/plugins/analysis-ik
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:5.6.3
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    hostname: kibana
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - "5601:5601"