version: '2'
services:
  rocketmq:
    image: registry.cn-hangzhou.aliyuncs.com/laizhenwei/rocketmq:4.2.0
    ports:
      - "9876:9876"
      - "10909:10909"
      - "10911:10911"
    environment:
      - "brokerIP1=本地ip"
    volumes:
      - '/Users/userName/data/rocketmq/store:/usr/local/rocketmq/store'

  rocketmq-console:
    image: registry.cn-hangzhou.aliyuncs.com/aluomaidi/rocketmq-console-ng:1.0.0
    ports:
      - "32773:8080"
    environment:
      - "JAVA_OPTS=-Drocketmq.namesrv.addr=ip:端口 -Dcom.rocketmq.sendMessageWithVIPChannel=false"